### ISSUE TITLE
wait statement improvement ("wait-on-until-for")

### ISSUE THREAD

**Issue by CradleOfPain** [TheClams/SmartVHDL#24]
VHDL allows combinations of the keywords `on`, `until` and `for` in wait statements.

 Currently any of the combinations including the `for` keyword causing Sublime Text to show an error highlight in the following `end` statements (see attached picture). 

![sublime_wait_err](https://user-images.githubusercontent.com/59475345/92116199-d1263780-edf3-11ea-8664-6100c7a829f6.JPG)

Minimal Example to copy:
``` VHDL
architecture tmp_arc of tmp is

  signal clk : std_logic;

begin

  test_proc: process is
  -- the for part causes an error highligh of the 'process' keyword in the next line
  wait on clk until clk = '1' for 20 ns; 
  end process;

end tmp_arc;
```

Removing the `for` statement from the line removes the error highlight. It's just an optical flaw and on some themes it is invisible
, but maybe this can be fixed easyly. I wasn't to successful myself, since I don't fully understand the syntax in the VHDL.sublime-syntax file. I guess it can be done with some minor changes around the following lines:

```YAML
    - match: \b(?i:wait)\b
      scope: keyword.language.vhdl
      push:
        - match: \b(?i:until|for)\b
          scope: keyword.language.vhdl
        - match: '(?=\S)'
          pop: true
```
